#开发环境配置
server:
  port:  8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
spring:
   http:
     encoding:
       charset: UTF-8
       enabled: true
       force: true
   datasource:
     driver-class-name: org.sqlite.JDBC
     url: jdbc:sqlite:data/data.db
     username:
     password:
     type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
     maxActive: 1
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
   aop:
     proxy-target-class: true
     #sqlite 查询报错 所以注释掉
     #poolPreparedStatements: false
     #maxOpenPreparedStatements: 20

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging  不同的目录不同的日志输出级别
logging:
  level:
    root: info
    com.wugz.app: info